name: aws_s3
description: A simple, convenient package for uploading to S3.
version: 0.0.1
homepage: https://github.com/cookooteam/aws_s3_upload

# aws mediaconvert import

protocol: rest-json

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  amazon_cognito_identity_dart_2: ^3.0.3
  http: ^0.13.5
  image_picker: 0.8.6
  path: ^1.8.2
  # aws mediaconvert import
  # shared_aws_api: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
